version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100
# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /home/ec2-user/express-app
# hooks:
#   ApplicationStop:
#     - location: scripts/application_stop.sh
#       timeout: 300
#       runas: ec2-user
#   BeforeInstall:
#     - location: scripts/before_install.sh
#       timeout: 300
#       runas: ec2-user
#   ApplicationStart:
#     - location: scripts/application_start.sh
#       timeout: 300
#       runas: ec2-user
